#!/bin/bash

CURDIR=$(readlink -f .)
SEQUENCE_FILE="$CURDIR/sequence"
DIRECTORY=$HOME/webphotos/$(basename $CURDIR)

mkdir -p $DIRECTORY
mkdir -p $DIRECTORY/thumbs

INDEX="$DIRECTORY/index.html"
echo "<html><head><title></title></head><body style='background:black'>" > $INDEX

TOTAL=$(wc -l <"$SEQUENCE_FILE")
CURRENT=1

#TODO: take a directory argument instead of just a list of files?
while read FILE; do
    BASENAME=$(basename "$FILE")
    OUTPUT_FILE="$DIRECTORY/$BASENAME"
    ORIENTATION=$(exiv2 -pv "$FILE" | grep Orientation | awk '{print $6}')
    THUMBNAIL="$DIRECTORY/thumbs/$BASENAME"
    case $ORIENTATION in
	1)
	    printf "(%3d/%3d) %s ... landscape\n" $CURRENT $TOTAL $FILE
	    convert $FILE -resize x100 $THUMBNAIL
	    convert $FILE -resize 1024 $OUTPUT_FILE
	    ;;
	8)
	    printf "(%3d/%3d) %s ... portrait\n" $CURRENT $TOTAL $FILE
	    convert $FILE -rotate 270 -resize 100 $THUMBNAIL
	    convert $FILE -rotate 270 -resize x1024 $OUTPUT_FILE
	    ;;
    esac
    echo "<a href='$BASENAME'><img src='thumbs/$BASENAME'/></a>" >> $INDEX
    CURRENT=$((CURRENT + 1))
done < "$SEQUENCE_FILE"

echo "</body></html>" >> $INDEX

if [ -e "$CURDIR/dc.yml" ]; then
    cp "$CURDIR/dc.yml" "$DIRECTORY"
fi
